/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPositionManager,
  IPositionManagerInterface,
} from "../IPositionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "int24",
        name: "lower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "upper",
        type: "int24",
      },
      {
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "feeGrowthInside0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeGrowthInside1",
        type: "uint256",
      },
    ],
    name: "positionMintCallback",
    outputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPositionManager__factory {
  static readonly abi = _abi;
  static createInterface(): IPositionManagerInterface {
    return new utils.Interface(_abi) as IPositionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPositionManager {
    return new Contract(address, _abi, signerOrProvider) as IPositionManager;
  }
}
