/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { NFTEscrow, NFTEscrowInterface } from "../NFTEscrow";

const _abi = [
  {
    inputs: [],
    name: "nftAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_idx",
        type: "uint256",
      },
    ],
    name: "precompute",
    outputs: [
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "predictedAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class NFTEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): NFTEscrowInterface {
    return new utils.Interface(_abi) as NFTEscrowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTEscrow {
    return new Contract(address, _abi, signerOrProvider) as NFTEscrow;
  }
}
