/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPrizeDistributionBuffer,
  IPrizeDistributionBufferInterface,
} from "../../../../../@pooltogether/v4-core/contracts/interfaces/IPrizeDistributionBuffer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "drawId",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct IPrizeDistributionSource.PrizeDistribution",
        name: "prizeDistribution",
        type: "tuple",
      },
    ],
    name: "PrizeDistributionSet",
    type: "event",
  },
  {
    inputs: [],
    name: "getBufferCardinality",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNewestPrizeDistribution",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        internalType: "struct IPrizeDistributionSource.PrizeDistribution",
        name: "prizeDistribution",
        type: "tuple",
      },
      {
        internalType: "uint32",
        name: "drawId",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOldestPrizeDistribution",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        internalType: "struct IPrizeDistributionSource.PrizeDistribution",
        name: "prizeDistribution",
        type: "tuple",
      },
      {
        internalType: "uint32",
        name: "drawId",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "drawId",
        type: "uint32",
      },
    ],
    name: "getPrizeDistribution",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        internalType: "struct IPrizeDistributionSource.PrizeDistribution",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrizeDistributionCount",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32[]",
        name: "drawIds",
        type: "uint32[]",
      },
    ],
    name: "getPrizeDistributions",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        internalType: "struct IPrizeDistributionSource.PrizeDistribution[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "drawId",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        internalType: "struct IPrizeDistributionSource.PrizeDistribution",
        name: "prizeDistribution",
        type: "tuple",
      },
    ],
    name: "pushPrizeDistribution",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "drawId",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "bitRangeSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "matchCardinality",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "startTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestampOffset",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxPicksPerUser",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiryDuration",
            type: "uint32",
          },
          {
            internalType: "uint104",
            name: "numberOfPicks",
            type: "uint104",
          },
          {
            internalType: "uint32[16]",
            name: "tiers",
            type: "uint32[16]",
          },
          {
            internalType: "uint256",
            name: "prize",
            type: "uint256",
          },
        ],
        internalType: "struct IPrizeDistributionSource.PrizeDistribution",
        name: "draw",
        type: "tuple",
      },
    ],
    name: "setPrizeDistribution",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPrizeDistributionBuffer__factory {
  static readonly abi = _abi;
  static createInterface(): IPrizeDistributionBufferInterface {
    return new utils.Interface(_abi) as IPrizeDistributionBufferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPrizeDistributionBuffer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPrizeDistributionBuffer;
  }
}
