/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAToken } from "./IAToken";
export type { IAaveIncentivesController } from "./IAaveIncentivesController";
export type { IInitializableAToken } from "./IInitializableAToken";
export type { IPool } from "./IPool";
export type { IPoolAddressesProvider } from "./IPoolAddressesProvider";
export type { IPoolAddressesProviderRegistry } from "./IPoolAddressesProviderRegistry";
export type { IScaledBalanceToken } from "./IScaledBalanceToken";
