/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface LibLiquidation extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): LibLiquidation;
  clone(): LibLiquidation;
  methods: {
    liquidationBalanceChanges(
      liquidatedBase: number | string | BN,
      liquidatedQuote: number | string | BN,
      amount: number | string | BN
    ): NonPayableTransactionObject<{
      _liquidatorQuoteChange: string;
      _liquidatorBaseChange: string;
      _liquidateeQuoteChange: string;
      _liquidateeBaseChange: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
