/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface Oracle extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Oracle;
  clone(): Oracle;
  methods: {
    decimals(): NonPayableTransactionObject<string>;

    latestAnswer(): NonPayableTransactionObject<string>;

    price(): NonPayableTransactionObject<string>;

    setDecimals(
      _decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    setPrice(_price: number | string | BN): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
