/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrizePool } from "./PrizePool";
export type { YieldSourcePrizePool } from "./YieldSourcePrizePool";
